### ISSUE TITLE
Overridable source paths for Tools

### ISSUE THREAD

**Issue by kenowessels** [spaceemotion/php-coding-standard#13]
sources should be overridable for tools.

```ini
source[] = src/Controllers
source[] = src/Models

parallel-lint[enabled] = true

phpstan[enabled] = true
phpstan[source][] = src/Controllers
```

in this case parallel-lint should be run on `src/Controllers` and `src/Models`
and phpstan on `src/Controllers` only

**Comment by spaceemotion** [comment]
I will probably change this so it works like "revert to original config". In which case the custom source config won't be passed along to the tool.
