### ISSUE TITLE
Rector is not working in actual version

### ISSUE THREAD

**Issue by Kalipso0505** [spaceemotion/php-coding-standard#18]
Hi :wave: 

![grafik](https://user-images.githubusercontent.com/3777168/167497248-8d73fbb5-07d9-4101-a665-d0884dbf0003.png)

`--output-file` option is missing for actual Rector version

![grafik](https://user-images.githubusercontent.com/3777168/167497046-784d5aa6-bccc-458b-89aa-1ac8d72c8372.png)

**Comment by spaceemotion** [comment]
This commit seems to be the culprit: https://github.com/rectorphp/rector-src/commit/a8ccfeb3d5cf251ae0c87f2bd9a461cd4bd84291

**Comment by Kalipso0505** [comment]
If the temporary file is necessary, maybe piping the std-output into one?

**Comment by Kalipso0505** [comment]
Vielen Dank, dass Du Dich darum gekümmert hast. Rector lässt sich nun über phpcstd nutzen.

Ich vermute allerdings noch ein Problem mit den return codes. Leider kann ich keinen präzise Schrittanleitung liefern. Vielleicht klingelt es bei Dir, wenn Du folgende Screenshots siehst?

![grafik](https://user-images.githubusercontent.com/3777168/168674958-35bc7212-0ab9-4d49-a064-c0d8cb529278.png)

**Comment by spaceemotion** [comment]
How does the output look like with -vvv enabled?

**Comment by Kalipso0505** [comment]
![grafik](https://user-images.githubusercontent.com/3777168/168757469-726e25bf-f8f7-4117-af04-e6911a1c7433.png)
