### ISSUE TITLE
[Suggestion] Add verbose mode

### ISSUE THREAD

**Issue by kenowessels** [spaceemotion/php-coding-standard#5]
It would be helpful to have a verbose mode which helps troubleshooting if a tool fails.

This could be done in different levels: 

`-v`: shows output of the tools if they fail.

`-vv`: allways shows output of tools.

**Comment by spaceemotion** [comment]
Closed in https://github.com/spaceemotion/php-coding-standard/commit/207bc9c9519a410da5df5769527ba4886c549fea
