### ISSUE TITLE
[Suggestion] Config - Define a "max-severity-gate" for every tool

### ISSUE THREAD

**Issue by kenowessels** [spaceemotion/php-coding-standard#6]
For some tools it would be beneficial for me if they won`t output breaking error warnings but still give me warnings.

If I have for example an old Codebase with lots of highly complex methods. I would love to show warnings in Pull-Requests by phpmd about the cyclomatic-complexity of the changed methods. But would still be able to merge the Pull Request.

To achieve this I would suggest a max-severity-gate for the different tools.
With this I could set the max-severity-gate to "warnings" for phpmd.
This would output a warning like this in Github:
![image](https://user-images.githubusercontent.com/1162201/81586958-a2083800-93b6-11ea-950e-54c62198a4d4.png)
But it would not Fail in the CI-Pipeline

This is just an Idea to tackle this problem. I would love to hear what you think about this @spaceemotion.

**Comment by kenowessels** [comment]
maybe `max-output-severity` is a better suited name.

**Comment by spaceemotion** [comment]
Differentiating between warnings or errors for the exit code is a bit more advanced that a simple "no-fail" flag that I've added for now. If you think that you still need the "severity gate", feel free to reopen this issue.
